### ISSUE TITLE
Does the code  finish all?

### ISSUE THREAD

**Issue by Ri-Bai** [NeurAI-Lab/MMC#1]
I do some try but can not find some files like'''od/modeling/head/ThunderNet''', I follow the readme to do some operation but some file not exist. Hoping for your reply and  interested in your this project.

**Comment by wlc-git** [comment]
Have you reproduced this code? I also have some problems and would like to consult you

**Comment by shruum** [comment]
Hi, this code is working for SSD detection network as of now. ThunderNet is not includes as it is quite slow.
Let me know what other issues you are facing, thanks.

**Comment by wlc-git** [comment]
Hello:

In train.py, config-file and --teacher-config-file need to be added. I don't know how to configure these two files.&nbsp;Looking forward to your reply!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NeurAI-Lab/MMC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 晚上8:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NeurAI-Lab/MMC] Does the code  finish all? (Issue #1)





 
Hi, this code is working for SSD detection network as of now. ThunderNet is not includes as it is quite slow.
 Let me know what other issues you are facing, thanks.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shruum** [comment]
There are some example configs in the code. But you need datasets and annotation files in the data directory structure shown in path: od/default_config/path_catlog.py 

I can upload the annotation files of the datasets and update the Readme also soon. 

- FLIR dataset
python train.py --config-file config/ssd_deit_thermal_mmc_FLIR.yaml --teacher-config-file config/ssd_deit_rgb_mmc_FLIR.yaml

-KAIST dataset
python train.py --config-file config/ssd_deit_thermal_mmc.yaml --teacher-config-file config/ssd_deit_rgb_mmc.yaml

**Comment by wlc-git** [comment]
Hello:

Recently, I encountered a small problem with the train.py code.&nbsp;For example,&nbsp;AssertionError: Invalid type &amp;lt;&nbsp;class 'NoneType'&amp;gt;&nbsp;for key MAX_EPOCHS;&nbsp;valid types = {&amp;lt;&nbsp;class 'tuple'&amp;gt;&nbsp;, &amp;lt;&nbsp;class 'list'&amp;gt;&nbsp;, &amp;lt;&nbsp;class 'str'&amp;gt;&nbsp;, &amp;lt;&nbsp;class 'int'&amp;gt;&nbsp;, &amp;lt;&nbsp;class 'float'&amp;gt;&nbsp;, &amp;lt;&nbsp;class 'bool'&amp;gt;&nbsp;}, how to solve this.&nbsp;Looking forward to your reply

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; wlc












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NeurAI-Lab/MMC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 晚上10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NeurAI-Lab/MMC] Does the code  finish all? (Issue #1)





 
There are some example configs in the code. But you need datasets and annotation files in the data directory structure shown in path: od/default_config/path_catlog.py
 
I can upload the annotation files of the datasets and update the Readme also soon.
  
FLIR dataset
 python train.py --config-file config/ssd_deit_thermal_mmc_FLIR.yaml --teacher-config-file config/ssd_deit_rgb_mmc_FLIR.yaml
  
-KAIST dataset
 python train.py --config-file config/ssd_deit_thermal_mmc.yaml --teacher-config-file config/ssd_deit_rgb_mmc.yaml
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
